from pathlib import Path
import re,json,html,unicodedata,os
ROOT=Path(__file__).parent; OUT=ROOT/'dist'; BASE=os.environ.get('SITE_URL','https://mnr-renovation-refonte.jules483909.chatgpt.site').rstrip('/')
def esc(s):return html.escape(str(s),quote=True)
def slug(s):return re.sub(r'[^a-z0-9]+','-',unicodedata.normalize('NFKD',s).encode('ascii','ignore').decode().lower()).strip('-')
articles=[];categories=[]
for line in (ROOT/'articles.txt').read_text().splitlines():
 if line.startswith('# '):cat=line[2:];categories.append(cat)
 elif line.strip():
  title,answer,observe,avoid,prepare=line.split('|');articles.append(dict(title=title,answer=answer,observe=observe,avoid=avoid,prepare=prepare,cat=cat,slug=slug(title)))
service_data=[
('menuiserie','Menuiserie intérieure','Des aménagements qui trouvent leur place.',15,'Portes, encadrements, rangements et plans de travail : une menuiserie réussie répond à vos habitudes autant qu’aux dimensions de votre intérieur. Dans une maison ancienne, les ajustements font toute la différence.','Nous étudions avec vous les éléments à conserver, les besoins de rangement et les finitions souhaitées. Les mesures prises sur place permettent de tenir compte des murs irréguliers, des niveaux et des ouvertures existantes.','Portes et boiseries|Rangements et étagères|Plans de travail|Plinthes et finitions',0),
('escaliers-parquets','Escaliers & parquets','Révéler le bois. Préserver le caractère.',15,'Un escalier patiné, un parquet usé ou des marches à reprendre peuvent retrouver leur place dans un intérieur repensé. La rénovation commence par une lecture attentive du bois et de ses assemblages.','Le choix entre conservation, réparation et remplacement part de l’état réel des éléments. Nous échangeons sur la teinte, le toucher et l’entretien pour définir une finition cohérente avec votre quotidien.','Rénovation d’escaliers|Restauration de planchers|Préparation du bois|Finitions et raccords',1),
('sablage-aerogommage','Sablage & aérogommage','Retrouver la matière sous les années.',8,'Peintures, vernis et anciennes finitions peuvent masquer la beauté du bois. Le sablage et l’aérogommage permettent d’étudier une nouvelle lecture de la matière, avec une méthode adaptée à chaque support.','Un essai aide à apprécier le rendu possible avant intervention. Essence, fragilité, reliefs et couches présentes orientent le choix du procédé. Les protections du chantier et la finition future sont prises en compte dès le départ.','Poutres et boiseries|Meubles en bois|Escaliers et éléments sculptés|Préparation avant finition',3),
('colombages','Colombages & façades','Le patrimoine normand mérite de l’attention.',6,'Les pans de bois font partie de l’identité des maisons normandes. Leur rénovation demande de regarder l’ensemble : pièces de bois, remplissages, ouvertures et cheminement de l’eau.','Nous préparons votre projet à partir de l’existant et des désordres observés. Les interventions touchant à la structure ou à d’autres métiers sont définies selon le diagnostic et les compétences nécessaires. Préserver la matière saine reste un point essentiel de la réflexion.','Rénovation de colombages|Lecture de l’existant|Préparation des bois|Finitions de façade',4),
('fenetres-portes','Fenêtres & portes','La bonne ouverture change le quotidien.',8,'Une fenêtre qui ferme correctement, une porte bien ajustée et des raccords soignés améliorent l’usage de votre maison. Bois ou PVC, le choix se fait en tenant compte de la façade et de vos priorités.','La visite permet de vérifier les dormants, les dimensions et les reprises à prévoir. Nous échangeons sur la lumière, l’ouverture, l’entretien et la ventilation pour construire une proposition adaptée au logement.','Menuiseries bois et PVC|Remplacement de fenêtres|Portes et réglages|Habillages et raccords',5),
('terrasses','Terrasses en bois','Prolonger la maison vers le jardin.',3,'Un coin repas, une transition vers le jardin, un espace pour profiter des beaux jours : la terrasse se dessine autour de votre manière de vivre dehors. Les niveaux et les circulations guident son implantation.','Structure, lames, rives et accès forment un ensemble. Nous regardons les seuils, l’évacuation de l’eau et les contraintes du terrain avant de choisir les matériaux et les finitions visibles.','Implantation et niveaux|Platelages en bois|Marches et rives|Raccords avec la maison',6),
('renovation-interieure','Rénovation intérieure','Des espaces qui vous ressemblent.',13,'Une entrée retrouvée, une salle de bains repensée, des boiseries remises en valeur : la rénovation intérieure relie confort d’usage et cohérence des matériaux. Vos photos de référence et vos contraintes donnent le point de départ.','Nous définissons avec vous le périmètre du projet, les éléments conservés et les interventions à coordonner. La plomberie, l’électricité et les autres travaux spécialisés sont à préciser selon les besoins du chantier.','Entrées et pièces de vie|Aménagements de salle de bains|Boiseries et finitions|Coordination du projet à définir',7),
]
category_images=[15,0,15,8,6,8,3,13,7,10]
category_descriptions=[
'Portes, rangements, boiseries et aménagements : comprendre les possibilités avant de transformer votre intérieur.',
'Préserver le caractère d’un escalier, comprendre ses défauts et choisir une finition adaptée au passage.',
'Identifier son parquet, préparer une rénovation et entretenir les sols en bois sans perdre leur caractère.',
'Choisir une méthode de décapage selon le support, organiser les protections et préparer la finition.',
'Observer les pans de bois, comprendre les interfaces de façade et préparer une rénovation respectueuse de l’existant.',
'Comparer les menuiseries, préparer la pose et penser lumière, usage et ventilation ensemble.',
'Concevoir les niveaux et les circulations, choisir le bois et entretenir une terrasse au fil des saisons.',
'Préparer une entrée, une salle de bains ou une pièce de vie en coordonnant matériaux, usages et étapes.',
'Formuler sa demande, lire un devis et organiser un chantier avec des décisions prises au bon moment.',
'Comprendre les finitions, reconnaître l’usure et conserver les bonnes références pour entretenir sa maison.'
]
def photo(n,alt,cls='',eager=False):
 return f'<img class="{cls}" src="/assets/photo-{n}-1280.webp" srcset="/assets/photo-{n}-640.webp 640w, /assets/photo-{n}-1280.webp 1280w" sizes="(max-width:650px) 100vw, 60vw" alt="{esc(alt)}" width="1280" height="960" loading="{"eager" if eager else "lazy"}" decoding="async"'+(' fetchpriority="high"' if eager else '')+'>'
def button(url,label,style=''):return f'<a class="button {style}" href="{url}">{label} <span aria-hidden="true">↗</span></a>'
def service_card(s):return f'<a class="card" href="/savoir-faire/{s[0]}/"><div class="photo">{photo(s[3],s[1]+" — chantier M.N.R Rénovation")}</div><div class="meta">SAVOIR-FAIRE · M.N.R</div><h3>{s[1]} <span aria-hidden="true">↗</span></h3><p>{s[4].split(". ")[0]}.</p></a>'
def article_card(a):
 n=category_images[categories.index(a['cat'])]
 return f'<a class="card" href="/blog/{a["slug"]}/"><div class="photo">{photo(n,"Chantier M.N.R Rénovation illustrant la catégorie "+a["cat"])}</div><div class="meta">{esc(a["cat"])} · 3 min</div><h3>{esc(a["title"])}</h3><p>{esc(a["answer"])}</p><span class="textlink">Lire le conseil ↗</span></a>'
def comparison(before,after,label):
 return f'<div class="compare"><img src="/assets/photo-{after}-1280.webp" alt="{esc(label)} après travaux" loading="lazy" width="1280" height="960"><img class="before" src="/assets/photo-{before}-1280.webp" alt="{esc(label)} avant travaux" loading="lazy" width="1280" height="960"><span class="label left">AVANT</span><span class="label right">APRÈS</span><span class="divider"></span><span class="handle" aria-hidden="true">‹ ›</span><input type="range" min="0" max="100" value="50" aria-label="Comparer avant et après : {esc(label)}" aria-valuetext="50 % de la photo avant"></div><div class="compare-caption"><strong>{label}</strong><span>Faites glisser pour comparer · Photos de chantier, points de vue différents.</span></div>'
def cta():return '<section class="cta"><div class="wrap"><div><p class="eyebrow">VOTRE MAISON A UNE HISTOIRE. ÉCRIVONS LA SUITE.</p><h2>Et si on parlait<br>de votre projet ?</h2><p>Quelques photos, une idée, une envie. Commençons par un échange.</p></div>'+button('/contact/','Contacter Quentin','dark')+'</div></section>'
def faq(items):return '<div class="faq">'+''.join(f'<details><summary>{esc(q)}</summary><p>{esc(a)}</p></details>' for q,a in items)+'</div>'
nav='<a href="/savoir-faire/">Nos savoir-faire</a><a href="/realisations/">Réalisations</a><a href="/a-propos/">L’entreprise</a><a href="/blog/">Le journal</a>'+button('/contact/','Parlons de votre projet')
brand='<a class="brand" href="/" aria-label="MNR Rénovation, accueil"><img src="/assets/logo.png" alt="Logo M.N.R Rénovation" width="110" height="74"><span>M.N.R<small>RÉNOVATION</small></span></a>'
header='<a class="skip" href="#contenu">Aller au contenu</a><div class="topbar"><div class="wrap"><span>ARTISAN MENUISIER · DOZULÉ, NORMANDIE</span><span>LE BOIS, NOTRE MATIÈRE. VOTRE MAISON, NOTRE ATTENTION.</span><a href="tel:+33604516618">06 04 51 66 18</a></div></div><header><div class="wrap nav">'+brand+'<button class="menu" aria-expanded="false" aria-controls="navigation">Menu ☰</button><nav id="navigation" class="navlinks" aria-label="Navigation principale">'+nav+'</nav></div></header>'
footer='<footer class="footer"><div class="wrap"><div class="footer-grid"><div>'+brand+'<p>Menuiserie, rénovation et travail du bois. Donner une nouvelle vie à l’existant, avec le goût du détail.</p><p>Dozulé · Calvados · Normandie</p></div><div><h3>NOS SAVOIR-FAIRE</h3>'+''.join(f'<a href="/savoir-faire/{s[0]}/">{s[1]}</a>' for s in service_data)+'</div><div><h3>À DÉCOUVRIR</h3><a href="/realisations/">Nos réalisations</a><a href="/a-propos/">M.N.R Rénovation</a><a href="/blog/">Le journal — nos conseils</a><a href="/contact/">Votre projet</a></div><div><h3>ÉCHANGEONS</h3><a href="tel:+33604516618">06 04 51 66 18</a><a href="mailto:quentinmaiseret@yahoo.fr">quentinmaiseret@yahoo.fr</a><p>7 impasse George Sand<br>14430 Dozulé</p></div></div><div class="footer-bottom"><span>© 2026 M.N.R Rénovation · Quentin Maiseret · SIRET 920 602 000 00019</span><span><a href="/mentions-legales/">Mentions légales & confidentialité</a></span></div></div></footer>'
organization={'@type':'HomeAndConstructionBusiness','@id':BASE+'/#entreprise','name':'M.N.R Rénovation','url':BASE+'/','telephone':'+33604516618','email':'quentinmaiseret@yahoo.fr','address':{'@type':'PostalAddress','streetAddress':'7 impasse George Sand','postalCode':'14430','addressLocality':'Dozulé','addressCountry':'FR'},'areaServed':{'@type':'AdministrativeArea','name':'Calvados'},'logo':BASE+'/assets/logo.png','founder':{'@type':'Person','name':'Quentin Maiseret'}}
pages=[]
def page(path,title,description,body,extra=None,crumb=None):
 url=BASE+path; graph=[organization,{'@type':'WebSite','@id':BASE+'/#site','url':BASE+'/','name':'M.N.R Rénovation','inLanguage':'fr-FR'},{'@type':'WebPage','@id':url+'#page','url':url,'name':title,'description':description,'inLanguage':'fr-FR','isPartOf':{'@id':BASE+'/#site'}}]
 if crumb:graph.append({'@type':'BreadcrumbList','itemListElement':[{'@type':'ListItem','position':i+1,'name':n,'item':BASE+u} for i,(n,u) in enumerate([('Accueil','/')]+crumb)]})
 if extra:graph.extend(extra)
 doc='<!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#222421"><title>'+esc(title)+'</title><meta name="description" content="'+esc(description)+'"><link rel="canonical" href="'+url+'"><meta property="og:title" content="'+esc(title)+'"><meta property="og:description" content="'+esc(description)+'"><meta property="og:url" content="'+url+'"><meta property="og:type" content="'+('article' if extra and extra[0].get('@type')=='BlogPosting' else 'website')+'"><meta property="og:locale" content="fr_FR"><link rel="icon" href="data:image/svg+xml,%3Csvg xmlns=%27http://www.w3.org/2000/svg%27 viewBox=%270 0 64 64%27%3E%3Crect width=%2764%27 height=%2764%27 rx=%278%27 fill=%27%23222421%27/%3E%3Ctext x=%2710%27 y=%2746%27 fill=%27%23d7ac59%27 font-size=%2744%27 font-family=%27serif%27%3EM%3C/text%3E%3C/svg%3E"><link rel="stylesheet" href="/style.css"><script type="application/ld+json">'+json.dumps({'@context':'https://schema.org','@graph':graph},ensure_ascii=False).replace('</','<\\/')+'</script><script defer src="/app.js"></script></head><body>'+header+'<main id="contenu">'+body+'</main>'+footer+'</body></html>'
 dest=OUT/path.strip('/')/'index.html' if path!='/' else OUT/'index.html';dest.parent.mkdir(parents=True,exist_ok=True);dest.write_text(doc);pages.append((path,title))
def pagehero(label,title,description,path):return '<section class="pagehero wrap reveal"><div class="breadcrumb"><a href="/">Accueil</a> / '+label+'</div><p class="eyebrow" style="margin-top:35px">'+label+'</p><h1>'+title+'</h1><p>'+description+'</p></section>'
faqhome=[('Quels travaux réalise M.N.R Rénovation ?','M.N.R Rénovation réalise des travaux de menuiserie bois et PVC, de rénovation d’escaliers et de planchers, de sablage, d’aérogommage et de colombages. Les réalisations présentent également des terrasses et des rénovations intérieures. Le périmètre de votre projet est défini ensemble avant devis.'),('Où se trouve l’entreprise ?','L’entreprise de Quentin Maiseret est située à Dozulé, dans le Calvados. Indiquez la commune de votre chantier lors du premier contact pour confirmer les possibilités d’intervention.'),('Peut-on conserver les éléments anciens ?','Lorsque leur état le permet, la conservation et la réparation peuvent être étudiées. Une visite permet de vérifier les supports et de déterminer ce qui peut être restauré et ce qui doit être remplacé.'),('Comment obtenir un devis ?','Contactez Quentin au 06 04 51 66 18 ou par email à quentinmaiseret@yahoo.fr. Quelques photos, votre commune et une description du besoin permettent de préparer le premier échange.'),('Quel budget prévoir pour une rénovation ?','Le budget dépend de l’état des supports, des dimensions, des accès, des matériaux et des finitions. Un devis adapté au chantier est plus utile qu’un prix générique au mètre carré.')]
home='<section class="hero"><img src="/assets/escalier-retouche.webp" alt="Escalier et boiseries rénovés, réalisation MNR Rénovation" width="1600" height="1200" fetchpriority="high"><div class="wrap reveal"><p class="eyebrow gold">LE SENS DU DÉTAIL. LE GOÛT DU TRAVAIL BIEN FAIT.</p><h1>Le charme de l’ancien.<br><span>Le confort de demain.</span></h1><p>Menuiserie, rénovation et travail du bois en Normandie. Redonnons du caractère à votre maison, sans perdre ce qui la rend unique.</p><div class="actions">'+button('/contact/','Discutons de votre projet')+button('/realisations/','Découvrir nos réalisations','outline')+'</div></div><div class="hero-note"><span>M.N.R RÉNOVATION — DOZULÉ, CALVADOS</span><span>Photographie de chantier<br>retouchée pour la lumière.</span></div></section><div class="trust"><div class="wrap"><span><b>01</b> Menuiserie bois & PVC</span><span><b>02</b> Rénovation & restauration</span><span><b>03</b> Sablage & aérogommage</span><span><b>04</b> Un artisan à votre écoute</span></div></div>'
home+='<section class="section wrap" id="savoir-faire"><div class="sectionhead"><div><p class="eyebrow">DU SAVOIR-FAIRE, À CHAQUE DÉTAIL</p><h2>Votre maison.<br>Tout notre savoir-faire.</h2></div><div><p>Restaurer ce qui compte. Repenser ce qui peut l’être. Du premier échange aux dernières finitions, votre projet commence par une attention portée à l’existant.</p><a class="textlink" href="/savoir-faire/">Explorer tous nos métiers ↗</a></div></div><div class="grid3">'+''.join(service_card(service_data[i]) for i in [1,3,5])+'</div></section>'
home+='<section class="darksection section"><div class="wrap split">'+photo(10,'Entrée rénovée avec boiseries sombres et sol ancien conservé')+'<div><p class="eyebrow gold">UN ARTISAN. UNE AUTRE FAÇON DE RÉNOVER.</p><h2>Le respect de l’existant.<br>L’exigence du détail.</h2><p>À Dozulé, Quentin Maiseret accompagne les projets de menuiserie et de rénovation sous le nom M.N.R Rénovation. Une porte ancienne, un escalier, une façade à colombages : chaque chantier commence par comprendre ce qui fait la singularité du lieu.</p><div class="steps"><div class="step"><strong>01</strong><div><h3>Échanger, avant de transformer</h3><p>Vos besoins, vos envies et les contraintes de la maison donnent la direction.</p></div></div><div class="step"><strong>02</strong><div><h3>Choisir la juste intervention</h3><p>Conserver, réparer ou remplacer : les choix se fondent sur l’état réel des matériaux.</p></div></div><div class="step"><strong>03</strong><div><h3>Soigner les derniers détails</h3><p>Jonctions, teintes et finitions donnent sa cohérence à l’ensemble.</p></div></div></div><a class="textlink" href="/a-propos/">Découvrir M.N.R Rénovation ↗</a></div></div></section>'
home+='<section id="realisations"><div class="section wrap" style="padding-bottom:35px"><div class="sectionhead"><div><p class="eyebrow">LA TRANSFORMATION, EN IMAGES</p><h2>Le même lieu.<br>Un nouveau regard.</h2></div><p>Des photos de nos chantiers, avant et après intervention. Faites coulisser le séparateur pour découvrir la transformation d’une façade à colombages.</p></div></div>'+comparison(4,6,'Rénovation d’un pignon à colombages')+'<div class="wrap" style="padding:30px 0 60px"><a class="textlink" href="/realisations/">Voir toutes les transformations ↗</a></div></section>'
home+='<section class="section wrap"><div class="sectionhead"><div><p class="eyebrow">L’INSPIRATION COMMENCE ICI</p><h2>Bien préparer.<br>Mieux rénover.</h2></div><div><p>Matériaux, entretien, étapes et choix de finition : des conseils concrets pour aborder vos travaux avec les bonnes questions.</p><a class="textlink" href="/blog/">Explorer les 100 articles du journal ↗</a></div></div><div class="grid3">'+''.join(article_card(articles[i]) for i in [10,40,60])+'</div></section><section class="section" style="background:#ebece5"><div class="wrap"><p class="eyebrow" style="text-align:center">AVANT DE COMMENCER</p><h2 style="text-align:center">Vos questions, nos repères.</h2>'+faq(faqhome)+'</div></section>'+cta()
page('/','M.N.R Rénovation | Menuisier à Dozulé, Calvados','Menuiserie, escaliers, parquets, colombages et sablage à Dozulé. Découvrez les réalisations de M.N.R Rénovation et échangez sur votre projet.',home,[{'@type':'FAQPage','mainEntity':[{'@type':'Question','name':q,'acceptedAnswer':{'@type':'Answer','text':a}} for q,a in faqhome]}])
page('/savoir-faire/','Nos savoir-faire | M.N.R Rénovation à Dozulé','Menuiserie bois et PVC, escaliers, parquets, colombages, terrasses et rénovation intérieure : découvrez les savoir-faire MNR à Dozulé.',pagehero('Nos savoir-faire','La matière, le geste.<br>Et votre projet.','De l’intérieur au jardin, nous regardons chaque projet dans son ensemble pour définir une intervention adaptée aux matériaux, à l’usage et au caractère de votre maison.','/savoir-faire/')+'<section class="wrap section" style="padding-top:15px"><div class="grid3">'+''.join(service_card(s) for s in service_data)+'</div></section>'+cta(),crumb=[('Nos savoir-faire','/savoir-faire/')])
for s in service_data:
 key,name,headline,n,intro,detail,features,ci=s; path='/savoir-faire/'+key+'/'
 body=pagehero('Nos savoir-faire · '+name,headline,intro,path)+'<section class="wrap section" style="padding-top:0"><div class="split">'+photo(n,name+' : réalisation MNR Rénovation',eager=True)+'<div><p class="eyebrow">'+name.upper()+'</p><h2>Un projet pensé<br>à partir de l’existant.</h2><p>'+detail+'</p><ul>'+''.join('<li>'+x+'</li>' for x in features.split('|'))+'</ul>'+button('/contact/','Parlons de votre projet')+'</div></div></section><section class="darksection section"><div class="wrap"><div class="sectionhead"><div><p class="eyebrow gold">DE L’IDÉE AUX FINITIONS</p><h2>Les bonnes décisions,<br>dans le bon ordre.</h2></div><p>Un chantier préparé permet de mieux anticiper les contraintes et de faire des choix cohérents avec votre budget et l’usage des lieux.</p></div><div class="grid3"><div><h3>01 · Comprendre le besoin</h3><p>Nous échangeons sur les difficultés actuelles, les éléments à préserver et le résultat souhaité. Des photos et des dimensions indicatives permettent de préparer la visite.</p></div><div><h3>02 · Définir l’intervention</h3><p>L’état du support, l’accès et les finitions orientent la proposition. Le devis précise les opérations prévues et les points qui demandent une vérification complémentaire.</p></div><div><h3>03 · Préparer la suite</h3><p>Les choix de teinte et de matériau s’anticipent. Les consignes d’entretien et les références des produits retenus vous aident à prendre soin du résultat après les travaux.</p></div></div></div></section><section class="section wrap"><div class="sectionhead"><div><p class="eyebrow">POUR ALLER PLUS LOIN</p><h2>Les conseils du journal.</h2></div><a class="textlink" href="/blog/categorie/'+slug(categories[ci])+'/">Tous les conseils de cette catégorie ↗</a></div><div class="grid3">'+''.join(article_card(a) for a in [x for x in articles if x['cat']==categories[ci]][:3])+'</div></section>'+cta()
 
 if key=='terrasses':
  body=body.replace('<section class="darksection section">','<figure class="wrap" style="margin-bottom:70px"><img src="/assets/terrasse-retouche.webp" alt="Terrasse en bois, photographie de chantier retouchée" width="1600" height="1200" loading="lazy"><figcaption class="fine">Photographie de chantier retouchée pour la lumière et la netteté. Les vues originales figurent dans nos réalisations.</figcaption></figure><section class="darksection section">',1)
 page(path,name+' à Dozulé | M.N.R Rénovation',intro[:155],body,[{'@type':'Service','name':name,'provider':{'@id':BASE+'/#entreprise'},'areaServed':'Calvados','url':BASE+path}],crumb=[('Nos savoir-faire','/savoir-faire/'),(name,path)])
projects=[('colombages','Colombages','Une façade retrouve ses lignes.',7,8,'Le bois remis en valeur, les ouvertures et les raccords redonnent une lecture cohérente à la façade. Ces images montrent l’évolution du chantier, avec les différences de lumière et de point de vue propres aux photographies prises sur place.'),('pignon','Colombages','Le caractère d’un pignon normand.',4,6,'Les pans de bois dessinent la façade et dialoguent avec le soubassement en brique. La comparaison permet de lire le travail sur l’ensemble, au-delà de la seule couleur de finition.'),('escalier','Escaliers','Retrouver la chaleur du bois.',0,15,'Marches en bois, rampe et colombages intérieurs composent un ensemble que la rénovation remet en valeur. Les traces du chantier laissent place à une entrée plus lisible et accueillante.'),('terrasse','Terrasses','Une nouvelle pièce, à ciel ouvert.',2,3,'L’espace extérieur se prolonge par une terrasse en bois. Le platelage et les niveaux organisent un lien entre les portes-fenêtres et le jardin, pour accueillir les usages du quotidien.'),('salle-de-bains','Intérieurs','Plus de lumière. Un nouvel usage.',12,13,'La salle de bains change de palette et d’organisation autour d’une douche, d’un meuble vasque et d’un miroir lumineux. Les photographies documentent la transformation de la pièce.'),('seconde-salle-de-bains','Intérieurs','Repenser une pièce essentielle.',17,16,'La baignoire et les anciens équipements laissent place à un aménagement repensé. Une rénovation se prépare à partir des dimensions disponibles, des réseaux et des habitudes des occupants.'),('entree','Intérieurs','Conserver l’âme, changer le regard.',9,10,'Le sol à motifs et les boiseries donnent à l’entrée une identité forte. Les couleurs profondes font ressortir les éléments anciens et relient l’escalier aux autres espaces de la maison.')]
body=pagehero('Réalisations','Des chantiers réels.<br>Des transformations visibles.','Escaliers, colombages, terrasses et intérieurs : parcourez les photos de nos réalisations et découvrez les étapes avant et après travaux.','/realisations/')+'<div class="wrap"><div class="pills" aria-label="Types de réalisations"><a href="#tous" class="active" data-project-filter="Tous">Tous</a>'+''.join('<a href="#'+slug(c)+'" data-project-filter="'+c+'">'+c+'</a>' for c in ['Colombages','Escaliers','Terrasses','Intérieurs'])+'</div><p class="fine">Les vues avant et après sont prises à des moments et sous des angles différents. Les comparateurs utilisent les photos originales, sans transformation générative.</p></div>'
for i,(key,cat,title,b,a,desc) in enumerate(projects):
 body+='<section class="project" data-category="'+cat+'" id="'+key+'"><div class="wrap section" style="padding-bottom:25px"><div class="sectionhead"><div><p class="eyebrow">'+cat.upper()+' · '+str(i+1).zfill(2)+'</p><h2>'+title+'</h2></div><p>'+desc+'</p></div></div>'+comparison(b,a,title)+'</section>'
body+='<section class="section wrap"><p class="eyebrow">SUR LE CHANTIER</p><h2>Les détails font l’ensemble.</h2><div class="grid3">'+''.join('<figure style="margin:0">'+photo(n,label)+'<figcaption class="fine" style="margin:15px 0">'+label+'</figcaption></figure>' for n,label in [(1,'Façade à colombages, vue d’ensemble'),(5,'Intervention sur le pan de bois'),(14,'Salle de bains : vue de la douche'),(11,'Photo partagée sur les réseaux à propos du chantier')])+'</div></section>'+cta()
page('/realisations/','Réalisations avant / après | M.N.R Rénovation','Découvrez les chantiers MNR en photos : colombages, escaliers, terrasses et salles de bains. Comparateurs avant / après pleine largeur.',body,crumb=[('Réalisations','/realisations/')])
body=pagehero('L’entreprise','Le bois, les maisons.<br>Et le goût du travail soigné.','M.N.R Rénovation, c’est l’entreprise de Quentin Maiseret, artisan menuisier installé à Dozulé dans le Calvados. Une activité tournée vers la rénovation, le bois et les détails qui donnent du caractère aux lieux.','/a-propos/')+'<section class="wrap section" style="padding-top:0"><div class="split">'+photo(8,'Façade rénovée par MNR, bois apparents et nouvelles finitions')+'<div><p class="eyebrow">ANCRÉ EN NORMANDIE</p><h2>Faire avec l’histoire<br>de votre maison.</h2><p>Les maisons anciennes ne se ressemblent pas. Leurs murs, leurs assemblages et leurs matériaux demandent une attention particulière avant de choisir une intervention. Notre approche commence par cet échange entre ce qui existe et ce que vous souhaitez faire évoluer.</p><p>Menuiserie bois et PVC, escaliers, parquets, sablage, aérogommage et colombages constituent les métiers présentés par M.N.R Rénovation. Les photos de chantier donnent à voir des transformations concrètes, des façades aux espaces intérieurs.</p><p>Vous échangez sur votre projet, ses priorités et ses contraintes. Les choix de matériaux et de finitions sont étudiés dans ce contexte, pour un résultat cohérent avec l’usage de la maison.</p>'+button('/realisations/','Voir les réalisations','dark')+'</div></div></section><section class="section darksection"><div class="wrap"><p class="eyebrow gold">NOTRE POINT DE DÉPART</p><h2>Écouter. Observer. Rénover.</h2><div class="grid3"><div><h3>Votre quotidien</h3><p>Une porte difficile à ouvrir, un escalier à restaurer, une pièce à repenser : nous partons de ce que vous souhaitez améliorer et des éléments que vous aimez déjà.</p></div><div><h3>La matière existante</h3><p>Le bois, ses finitions et ses assemblages guident les possibilités. Le diagnostic aide à faire la différence entre un changement d’aspect et une réparation nécessaire.</p></div><div><h3>Un projet défini ensemble</h3><p>Le devis et les échanges précisent les interventions, les accès et les finitions. Les éventuels besoins d’autres métiers sont identifiés selon le chantier.</p></div></div></div></section><section class="section wrap"><div class="split"><div><p class="eyebrow">DOZULÉ · CALVADOS</p><h2>Commençons<br>par une conversation.</h2><p>Indiquez votre commune, le type de travaux et vos disponibilités. Quelques photographies permettent de préparer un échange avant une éventuelle visite. Les possibilités d’intervention et le calendrier sont à confirmer selon votre projet.</p><p><strong>Quentin Maiseret — M.N.R Rénovation</strong><br>7 impasse George Sand, 14430 Dozulé<br>SIRET : 920 602 000 00019</p>'+button('/contact/','Présenter mon projet')+'</div>'+photo(3,'Terrasse en bois réalisée devant une maison')+'</div></section>'+cta()
page('/a-propos/','Quentin Maiseret, artisan à Dozulé | M.N.R Rénovation','Découvrez MNR Rénovation, l’entreprise de Quentin Maiseret à Dozulé : menuiserie bois et PVC, restauration et rénovation dans le Calvados.',body,crumb=[('L’entreprise','/a-propos/')])
body=pagehero('Contact','Une idée, une envie ?<br>Parlons de votre maison.','Décrivez les travaux que vous envisagez. Quelques informations suffisent pour préparer un premier échange avec Quentin et préciser les prochaines étapes.','/contact/')+'<section class="wrap section" style="padding-top:0"><div class="contact-grid"><div><p class="eyebrow">UN CONTACT DIRECT</p><a class="contact-phone" href="tel:+33604516618">06 04 51 66 18</a><p><a class="textlink" href="mailto:quentinmaiseret@yahoo.fr">quentinmaiseret@yahoo.fr</a></p><p>M.N.R Rénovation · Quentin Maiseret<br>7 impasse George Sand<br>14430 Dozulé, Calvados</p><h3>Pour préparer notre échange</h3><p>Précisez votre commune, les pièces concernées et ce que vous souhaitez conserver ou transformer. Vous pourrez joindre des photos directement dans votre messagerie.</p><p>Le budget, les délais et le périmètre sont étudiés selon l’état des supports et les contraintes du chantier. Les dimensions transmises à distance restent indicatives avant un relevé sur place.</p>'+photo(15,'Escalier en bois restauré et colombages intérieurs')+'</div><form id="contact-form" class="contact-box"><h2 style="font-size:2rem">Votre projet commence ici.</h2><p>Ce formulaire prépare un email dans votre messagerie. Vous le relisez avant de l’envoyer.</p><label for="name">Votre nom *</label><input id="name" name="name" autocomplete="name" required maxlength="100"><label for="email">Votre email *</label><input id="email" name="email" type="email" autocomplete="email" required maxlength="180"><label for="town">Commune du chantier *</label><input id="town" name="town" autocomplete="address-level2" required maxlength="100"><label for="project">Type de projet</label><select id="project" name="project">'+''.join('<option>'+s[1]+'</option>' for s in service_data)+'<option>Autre projet</option></select><label for="message">Décrivez votre projet *</label><textarea id="message" name="message" required minlength="15" maxlength="4000" placeholder="La pièce, les travaux envisagés, les éléments à conserver…"></textarea><p class="fine">Les champs marqués * sont nécessaires. Aucune information n’est envoyée par ce site ; votre application email prend le relais.</p><button class="button dark" type="submit">Préparer mon email ↗</button><p id="form-status" role="status"></p><a href="mailto:quentinmaiseret@yahoo.fr" class="fine textlink">Ou écrire directement à Quentin</a></form></div></section>'
page('/contact/','Contact et demande de devis | M.N.R Rénovation','Contactez Quentin Maiseret au 06 04 51 66 18 pour votre projet de menuiserie ou rénovation à Dozulé et dans le Calvados.',body,crumb=[('Contact','/contact/')])
def pills(active=None):return '<nav class="pills" aria-label="Catégories du journal"><a href="/blog/"'+(' class="active"' if active is None else '')+'>Tous les conseils</a>'+''.join('<a href="/blog/categorie/'+slug(c)+'/"'+(' class="active"' if c==active else '')+'>'+c+'</a>' for c in categories)+'</nav>'
body=pagehero('Le journal','Les bonnes questions.<br>Les bons gestes.','100 articles pour préparer vos travaux, comprendre les matériaux et prendre soin de votre maison. Choisissez un métier ou une étape de votre projet.','/blog/')+'<section class="wrap" style="padding-bottom:90px">'+pills()+'<div class="blog-summary"><strong>100 conseils · 10 catégories</strong><span>Du premier projet à l’entretien quotidien.</span></div>'
for c in categories:
 items=[a for a in articles if a['cat']==c]
 body+='<section class="journal-category"><div class="sectionhead"><div><p class="eyebrow">10 ARTICLES</p><h2>'+c+'</h2><p>'+category_descriptions[categories.index(c)]+'</p></div><a class="textlink" href="/blog/categorie/'+slug(c)+'/">Explorer la catégorie ↗</a></div><div class="grid3">'+''.join(article_card(a) for a in items[:3])+'</div><div class="article-links">'+''.join('<a href="/blog/'+a['slug']+'/">'+a['title']+' <span aria-hidden="true">↗</span></a>' for a in items[3:])+'</div></section>'
body+='</section>'+cta()
page('/blog/','Le journal : 100 conseils rénovation | M.N.R Rénovation','100 articles sur la menuiserie, les escaliers, les colombages, le parquet, le sablage et la rénovation. Des conseils classés en 10 catégories.',body,crumb=[('Le journal','/blog/')])
for ci,c in enumerate(categories):
 path='/blog/categorie/'+slug(c)+'/'
 body=pagehero('Le journal · '+c,c,category_descriptions[ci],path)+'<section class="wrap section" style="padding-top:0">'+pills(c)+'<div class="grid3">'+''.join(article_card(a) for a in articles if a['cat']==c)+'</div></section>'+cta()
 page(path,c+' : conseils et guides | M.N.R Rénovation',category_descriptions[ci],body,crumb=[('Le journal','/blog/'),(c,path)])
category_notes=[
('Penser usage et proportions','Une menuiserie intérieure s’inscrit dans un espace déjà habité. Avant de choisir un matériau, vérifiez les passages, les débattements et les éléments qui doivent rester accessibles. Un radiateur, une prise ou une porte voisine peuvent imposer un ajustement. Les murs anciens demandent souvent un relevé à plusieurs endroits : une seule largeur ne suffit pas toujours. Le bon projet relie l’usage quotidien à des détails de finition cohérents avec le reste de la pièce.'),
('Regarder l’escalier comme un ensemble','Marches, contremarches, limons et rampe fonctionnent ensemble. Une intervention esthétique doit donc rester cohérente avec leur état et leur stabilité. Le choix de finition s’accompagne d’une réflexion sur le passage, le nettoyage et les temps d’immobilisation. Dans une maison occupée, ces contraintes se préparent avant le chantier. Si un élément bouge de façon inhabituelle ou semble fragilisé, une vérification sur place est nécessaire avant de poursuivre la rénovation de surface.'),
('Identifier le sol avant de choisir la méthode','La construction du parquet, son épaisseur disponible et sa finition déterminent les possibilités de rénovation. Regardez les zones près des seuils et les endroits déjà réparés : ils peuvent donner des indications sur les couches présentes. Un défaut de support ou une entrée d’eau doit être compris avant la remise en état. Le choix d’une teinte ne vient qu’après ces vérifications. Conserver les références de la finition facilitera ensuite le nettoyage et les éventuelles reprises.'),
('Définir le résultat avant le procédé','Un décapage se juge sur la préservation du support autant que sur la disparition de l’ancienne couche. La méthode doit être adaptée au bois, aux reliefs et aux revêtements présents. Un essai permet de discuter du rendu réellement accessible. Les anciennes peintures inconnues nécessitent une évaluation avant les travaux susceptibles de produire des poussières. Les protections, le nettoyage et la finition après décapage doivent être précisés pour comprendre le périmètre complet de l’intervention.'),
('Observer les interfaces du bâtiment','Le bois d’une façade ne se comprend pas isolément. Les remplissages, les appuis, les évacuations et les raccords autour des ouvertures influencent son exposition à l’eau. Une finition neuve ne corrige pas une cause d’humidité persistante. L’examen doit aussi distinguer les marques anciennes des évolutions récentes. Les interventions sur des pièces porteuses demandent une évaluation adaptée. Garder des photos datées et les informations sur les travaux précédents aide à préparer un projet de conservation cohérent.'),
('Considérer la fenêtre complète et sa pose','Le confort dépend du vitrage, du cadre, des raccords et de la précision de la pose. Il faut également tenir compte du renouvellement d’air du logement. La comparaison de produits gagne donc à porter sur des ensembles équivalents, avec des dimensions et des performances clairement identifiées. Avant commande, les cotes, les sens d’ouverture et les finitions périphériques doivent être confirmés. Les photos aident à préparer la discussion, mais elles ne remplacent pas le relevé nécessaire sur place.'),
('Préparer ce qui restera sous les lames','La partie visible d’une terrasse repose sur une structure dont la conception est essentielle. Les niveaux, les appuis, les fixations et la circulation de l’eau doivent être étudiés ensemble. Le projet doit aussi permettre l’entretien et l’accès aux équipements existants. Le bois change d’aspect à l’extérieur : mieux vaut décider dès le départ si cette patine est souhaitée ou si un programme d’entretien sera suivi. Les détails de rive et de seuil se prévoient avant la pose.'),
('Coordonner les étapes et les métiers','Une rénovation intérieure réussie évite de refermer une surface avant d’avoir réglé ce qui se trouve derrière. Les supports, les réseaux et les contraintes d’humidité doivent être regardés avant les finitions décoratives. Le périmètre de chaque intervenant mérite d’être clair, notamment dans une salle de bains. Les mesures définitives se prennent au bon moment, en tenant compte des épaisseurs ajoutées. Conserver les éléments anciens choisis suppose aussi de les protéger pendant les phases de travaux voisines.'),
('Comparer des périmètres réellement équivalents','Un devis utile décrit ce qui sera fait, sur quels supports et avec quelles finitions. Les accès, les protections et les déposes peuvent modifier le temps nécessaire. Dans l’ancien, certaines informations ne deviennent visibles qu’après ouverture ou démontage. Il est donc utile de prévoir comment une découverte sera signalée et comment une intervention complémentaire sera validée. Des choix de matériaux pris à temps et un dossier de photos clair facilitent la préparation du chantier et les échanges.'),
('Conserver la référence de la finition','L’entretien d’un matériau dépend du système réellement appliqué. Une apparence mate, brillante ou naturelle ne permet pas toujours d’identifier un produit. Garder la référence, la date d’application et les consignes du fabricant évite des mélanges incompatibles. Une observation régulière permet de repérer l’usure avant qu’elle n’atteigne profondément le support. Les essais discrets et les méthodes douces sont utiles, mais une dégradation qui évolue ou une humidité persistante demandent d’abord de comprendre la cause.')
]
source_links={3:('INRS — interventions sur les peintures contenant du plomb','https://www.inrs.fr/media?refINRS=ED+6374'),4:('Ministère de la Culture — recommandations pour le bâti ancien','https://www.culture.gouv.fr/Media/medias-creation-rapide/Cahiers-de-recommandations_Renovation-energetique-de-l-habitat-ancien-en-CVL.pdf'),5:('France Rénov’ — remplacer les portes et fenêtres','https://france-renov.gouv.fr/renovation/isolation/portes-fenetres-maison'),6:('FCBA — finition et entretien des bois en extérieur','https://www.fcba.fr/wp-content/uploads/2022/10/guide-technique-finition-bois-2022.pdf'),9:('FCBA — guide des finitions du bois','https://www.fcba.fr/wp-content/uploads/2022/10/guide-technique-finition-bois-2022.pdf')}
for a in articles:
 ci=categories.index(a['cat']);path='/blog/'+a['slug']+'/';catpath='/blog/categorie/'+slug(a['cat'])+'/';related=[x for x in articles if x['cat']==a['cat'] and x!=a];idx=next(i for i,x in enumerate(articles) if x==a);related=related[idx%7:idx%7+3] or related[:3]
 service=next((s for s in service_data if s[7]==ci),service_data[1] if ci==2 else service_data[0]);noteheading,note=category_notes[ci]
 body='<section class="pagehero wrap reveal"><div class="breadcrumb"><a href="/">Accueil</a> / <a href="/blog/">Le journal</a> / <a href="'+catpath+'">'+a['cat']+'</a></div><p class="eyebrow" style="margin-top:35px">'+a['cat'].upper()+' · CONSEIL PRATIQUE</p><h1>'+a['title']+'</h1><p class="fine">Publié le 22 septembre 2026 · Rédaction M.N.R Rénovation · 3 min de lecture</p></section><div class="wrap article-layout section" style="padding-top:0"><article class="article"><div class="answer"><strong>À retenir</strong><p>'+a['answer']+'</p></div><h2 id="observer">Ce qu’il faut regarder</h2><p>'+a['observe']+'</p><figure>'+photo(category_images[ci],'Photo de chantier MNR illustrant la catégorie '+a['cat'])+'<figcaption>Photographie M.N.R Rénovation — illustration de la catégorie '+a['cat'].lower()+'.</figcaption></figure><h2 id="eviter">Le point de vigilance</h2><p>'+a['avoid']+'</p><h2 id="contexte">'+noteheading+'</h2><p>'+note+'</p><h2 id="preparer">Préparer votre projet</h2><p>'+a['prepare']+'</p><p>Pour un projet à Dozulé ou dans le Calvados, précisez votre commune et les contraintes d’accès lors du premier échange avec M.N.R Rénovation. Une vue générale et quelques détails aident à préparer les questions. Les mesures et l’état du support sont à confirmer sur place avant de définir une intervention.</p><div class="answer"><strong>Votre prochaine étape</strong><p>Rassemblez vos observations et vos photos, puis <a class="textlink" href="/contact/">présentez votre projet à Quentin</a>. Le choix d’une solution dépend de l’existant, de vos priorités et de la finition attendue.</p></div>'
 if ci in source_links:
  label,url=source_links[ci];body+='<h3>Pour approfondir</h3><p class="fine">Ressource de référence sur le sujet : <a class="textlink" href="'+url+'" target="_blank" rel="noopener noreferrer">'+label+'</a>. Les prescriptions du produit et le diagnostic du chantier restent déterminants.</p>'
 body+='</article><aside class="aside"><p class="eyebrow">DANS CET ARTICLE</p><a href="#observer">Ce qu’il faut regarder</a><a href="#eviter">Le point de vigilance</a><a href="#contexte">'+noteheading+'</a><a href="#preparer">Préparer votre projet</a><hr><h3>Un projet en tête ?</h3><p>Parlons de votre maison et des travaux que vous envisagez.</p>'+button('/contact/','Nous contacter')+'<a class="textlink" href="/savoir-faire/'+service[0]+'/">Découvrir : '+service[1]+'</a></aside></div><section class="wrap section"><p class="eyebrow">POURSUIVRE LA LECTURE</p><h2>Des conseils qui se complètent.</h2><div class="grid3">'+''.join(article_card(x) for x in related)+'</div><p><a class="textlink" href="'+catpath+'">Tous les articles : '+a['cat']+' ↗</a></p></section>'+cta()
 page(path,a['title']+' | M.N.R Rénovation',a['answer'][:160],body,[{'@type':'BlogPosting','headline':a['title'],'description':a['answer'],'datePublished':'2026-09-22','dateModified':'2026-09-22','author':{'@type':'Organization','name':'Rédaction M.N.R Rénovation','url':BASE+'/a-propos/'},'publisher':{'@id':BASE+'/#entreprise'},'mainEntityOfPage':{'@id':BASE+path+'#page'},'articleSection':a['cat'],'inLanguage':'fr-FR','image':BASE+'/assets/photo-'+str(category_images[ci])+'-1280.webp'}],crumb=[('Le journal','/blog/'),(a['cat'],catpath),(a['title'],path)])
body=pagehero('Informations','Mentions légales<br>& confidentialité.','Les informations utiles pour identifier l’entreprise et comprendre le fonctionnement de ce site.','/mentions-legales/')+'<section class="wrap section article" style="padding-top:0;max-width:850px"><h2>Éditeur</h2><p>MONSIEUR QUENTIN MAISERET, entrepreneur individuel, sous le nom M.N.R Rénovation.<br>7 impasse George Sand, 14430 Dozulé, France.<br>SIREN : 920 602 000 · SIRET : 920 602 000 00019.<br>Activité : travaux de menuiserie bois et PVC, code APE 4332A.<br>Téléphone : <a href="tel:+33604516618">06 04 51 66 18</a>.<br>Email : <a href="mailto:quentinmaiseret@yahoo.fr">quentinmaiseret@yahoo.fr</a>.</p><h2>À propos de cette version</h2><p>Cette version de présentation est hébergée via Sites sur une adresse chatgpt.site. Les informations d’hébergement et les documents contractuels doivent être adaptés lors de la mise en service sur le domaine définitif. Le site historique reste accessible sur <a class="textlink" href="https://www.mnr-renovations.fr/">mnr-renovations.fr</a>.</p><h2>Demandes de contact</h2><p>Le formulaire prépare un message dans votre logiciel de messagerie. Le site n’enregistre pas les champs et n’envoie pas lui-même d’email. Vous choisissez de transmettre le message et les éventuelles pièces jointes à l’entreprise. Vous pouvez contacter l’éditeur pour toute question sur les informations ainsi communiquées.</p><h2>Cookies et services tiers</h2><p>Le code de ce site n’ajoute pas de mesure d’audience ni de cookies publicitaires. L’accès à cette version privée peut utiliser les mécanismes d’authentification de la plateforme d’hébergement. Les polices sont servies localement avec le site.</p><h2>Photographies et contenus</h2><p>Les photographies proviennent des fichiers transmis pour la refonte et du site historique M.N.R Rénovation. Les comparaisons avant et après présentent des vues de chantier dont les angles et la lumière peuvent différer. Les images retouchées sont signalées lorsqu’elles sont utilisées.</p><h2>Conseils et prestations</h2><p>Les articles proposent des repères pour préparer un projet. Ils ne remplacent ni un diagnostic sur place, ni les prescriptions des fabricants. Les prestations, leur prix et leurs conditions sont définis dans les documents convenus avec l’entreprise.</p><p><a class="textlink" href="https://www.mnr-renovations.fr/cgv">Consulter les CGV du site historique</a></p></section>'
page('/mentions-legales/','Mentions légales et confidentialité | M.N.R Rénovation','Identité de MNR Rénovation, coordonnées de Quentin Maiseret et informations sur le fonctionnement du site et du formulaire de contact.',body,crumb=[('Mentions légales','/mentions-legales/')])
notfound=header+'<main class="wrap pagehero"><p class="eyebrow">PAGE INTROUVABLE</p><h1>Cette page n’existe pas.</h1><p>Retrouvez nos réalisations, nos métiers ou les conseils du journal.</p>'+button('/','Revenir à l’accueil')+'</main>'+footer
(OUT/'404.html').write_text('<!doctype html><html lang="fr"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Page introuvable | M.N.R</title><meta name="robots" content="noindex"><link rel="stylesheet" href="/style.css">'+notfound+'<script src="/app.js"></script></html>')
(OUT/'sitemap.xml').write_text('<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+''.join('<url><loc>'+esc(BASE+p)+'</loc><lastmod>2026-09-22</lastmod></url>' for p,t in pages)+'</urlset>')
(OUT/'robots.txt').write_text('User-agent: *\nAllow: /\nSitemap: '+BASE+'/sitemap.xml\n')
(OUT/'llms.txt').write_text('# M.N.R Rénovation\n\n> Entreprise de Quentin Maiseret, menuiserie bois et PVC et rénovation à Dozulé, Calvados.\n\nTéléphone : +33 6 04 51 66 18\nEmail : quentinmaiseret@yahoo.fr\nAdresse : 7 impasse George Sand, 14430 Dozulé\nSIRET : 92060200000019\n\n## Pages principales\n'+''.join('- ['+t+']('+BASE+p+')\n' for p,t in pages if '/blog/' not in p)+'\n## Journal : 100 conseils en 10 catégories\n'+''.join('- ['+c+']('+BASE+'/blog/categorie/'+slug(c)+'/)\n' for c in categories)+'\nLes articles donnent des repères généraux ; les prestations sont définies après examen du projet. Les images avant/après sont des photos de chantier, avec des angles parfois différents. Aucun prix générique ni certification non vérifiée ne sont annoncés.\n')
(OUT/'_redirects').write_text('/cgv /mentions-legales/ 301\n')
(ROOT/'pages.json').write_text(json.dumps(pages,ensure_ascii=False,indent=2))
print(f'{len(pages)} pages HTML generated, {len(articles)} articles, {len(categories)} categories.')
